### ISSUE TITLE
Put universal header styles in DC

### ISSUE THREAD

**Issue by gabrielhl** [zalando/dress-code#134]
DC is already a dependency for  [Solution Center Header](https://github.com/zalando/solution-center-header). It would make sense for the styling code for the header to be inside of DC.

**Comment by gabrielhl** [comment]
I've started this task in a branch [topic/dc-header](https://github.com/zalando/dress-code/tree/topic/dc-header). Would appreciate any input and help. @xonic @cjhowald @dami-gg @rbarilani

**Comment by rbarilani** [comment]
@gabrielhl Ok If: brand element is removed. It make sense to put the code here if it's a reusable "navbar" not strictly bound with our products.

**Comment by gabrielhl** [comment]
@rbarilani What do you mean? The Zalando brand? Or the products list?

**Comment by rbarilani** [comment]
@gabrielhl I mean the brand sub element... but more in general the header molecule can live in this repo if it's something reusable as the bootstrap navbar.

**Comment by gabrielhl** [comment]
I agree, "our" Solution Center Header should be an implementation with added specificity and content, of a general dc-header. Or maybe should be called dc-navbar or something like this.

**Comment by rbarilani** [comment]
@gabrielhl  +1 for dc-navbar

**Comment by gabrielhl** [comment]
Not relevant right now, especially with CS working to make the header not dependant on DC.
