### ISSUE TITLE
Gzip CSS for distribution

### ISSUE THREAD

**Issue by dami-gg** [zalando/dress-code#136]
Apart from minifying it we should also Gzip it in order to increasing loading speed when using the distributed CSS in the applications.

https://css-tricks.com/the-difference-between-minification-and-gzipping/

**Comment by rbarilani** [comment]
@dami-gg For what I know gzipping is a process done by the web-server that "serve" the assets. The server compress and cache the requested file and then the browser uncompress that file when is received. If that is right is not up to us to provide a gzipped version.

@mrac Can you confirm that assumption?

**Comment by mrac** [comment]
Yes, HTTP compression just needs to be turned on in the web server. In that case the response header will contain "Content-Encoding: gzip". Most web servers support gzip compression option.
