### ISSUE TITLE
Update readme to include tips for font size

### ISSUE THREAD

**Issue by cjhowald** [zalando/dress-code#140]
Right now, to achieve proper sizing, the `<html>` and `<body>` tags have to have classes `dc-html` and `dc-body` applied, respectively. We should add this to the usage steps.

**Comment by mrac** [comment]
+1

**Comment by rbarilani** [comment]
Yep we should fix that... if we cannot remove this mandatory step... what do you think if we adopt a pragmatic applying directly the mixins to html and body tag? @cjhowald @mrac 

p.s. I talk to @xonic (thomas) before my holidays and it seems the dc-html mixin is really required and must be applied to the html tag. The dc-body mixin instead could be applied to every container element.

**Comment by rbarilani** [comment]
This will be solved with 1.0.0 beta, the fix is already merged in the 1.0.0 beta branch.
