### ISSUE TITLE
Publish on npm and bower

### ISSUE THREAD

**Issue by rbarilani** [zalando/dress-code#145]
Publish the package in bower and npm registry. @cjhowald I noticed that the solution header is published on bower and npm? do we have a zalando user for publishing?

**Comment by cjhowald** [comment]
I just used a personal npm account to publish. Did some digging on npm and I see there is a [zalando user](https://www.npmjs.com/~zalando). Looks like it is connected to @prayerslayer. Perhaps he can shed some insight.

**Comment by rbarilani** [comment]
I asked to @prayerslayer and he confirmed that we don't have a npm organization. So we should publish with our personal account.

**Comment by rbarilani** [comment]
closed with https://github.com/zalando/dress-code/commit/658bf3721928380bd263dde129358deac728bdf1
