### ISSUE TITLE
Components List for 1.0.0-alpha

### ISSUE THREAD

**Issue by rbarilani** [zalando/dress-code#16]
Components that must or should be implemented in 1.0.0:

- [x] ~~responsive grid, responsive utility classes (ex. hide-md)~~ (moved to 1.0.0-alpha.1)
- [x] divider
- [x] buttons (small, medium, big, block, icon button, with icon and text... etc)
- [x] button group
- [x] icons (font icon)
- [x] dropdown, dropup
- [x] input group 
- [x] **progress bar (high priority)**
- [x] **spinner/loader (high priority)**
- [x] ~~thumbnails~~ (removed: not a use case)
- [x] ~~avatar~~ (removed: not a use case)
- [x] ~~autocomplete~~ (removed: not a use case)
- [x] **dialog (high priority)** 
- [x] card
- [x] tooltip
- [x] messages/alert
- [x] **toast (high priority)**
- [x] ~~sticky list headers~~  (removed: not a use case)

**Comment by gabrielhl** [comment]
It was closed by a merge for the buttons, should not have closed, I'm reopening.

**Comment by gabrielhl** [comment]
The search-form component that's already in the styleguide has a "suggestion" system that could work for autocomplete. What do you think?

**Comment by gabrielhl** [comment]
@rbarilani What did you mean by sticky header/sticky viewport?

**Comment by rbarilani** [comment]
@gabrielhl Yep the name is not correct, probably is subheader..... something like this: https://material.angularjs.org/latest/demo/subheader

Could be fixed or relative.... this be will be driven by javascript....

**Comment by gabrielhl** [comment]
Ah OK so like a sticky list header.

**Comment by rbarilani** [comment]
@gabrielhl  Ok let's remove the avatar what do you think about thumbnails?
