### ISSUE TITLE
Toast Message Animation Style Broken When Shown Less Than 4 Seconds

### ISSUE THREAD

**Issue by cjhowald** [zalando/dress-code#169]
Showing a toast message for less than 4 seconds breaks the hide animation. The message disappears suddenly (rather than sliding up) to reveal a small black border which then slides off.

The problem appears to come from the dress code assuming a 4 second animation:
```
@mixin dc-toast--top {
    animation: dc-toast-animation--top 4s 1 forwards;
}

@mixin dc-toast--bottom {
    padding: $dc-space75 $dc-space100 0;
    animation: dc-toast-animation--bottom 4s 1 forwards;
}
```

However, the animation length is configurable in the messaging service.

**Comment by cjhowald** [comment]
It's hard to capture this in a screenshot, since it is an animation issue. To see it live:

1. Go to usf-dev.norris.zalan.do and log in.
2. Add at least one brand favorite using the search form.
3. Delete the favorite by clicking edit then the trash icon.

Note: your user must have access to at least 2 brands to see this page. Contact team norris if you need a user or additional rights.

**Comment by gabrielhl** [comment]
Just pushed a branch witha suggested fix for this.
