### ISSUE TITLE
style(patterns): establish a naming convention for patterns

### ISSUE THREAD

**Issue by rbarilani** [zalando/dress-code#172]
Right now with 1.0.0 beta branch we are using dc--whatever for patterns. (common modifiers that can be applied to every elements).

IHMO we could use also not BEM naming using for example ```dc-text-center``` but then it's not so obvious to distinguish between patterns and blocks (one of the good thing of BEM naming conventions is that watching the class names you are able to understand what is what).

So... IHMO we should use dc--<pattern-name>.

Examples:

```
dc-text-center
dc-text-left
dc-truncate
dc-islands-75
```

to

```
dc--text-center
dc--text-left
dc--truncate
dc--islands-75
```

@gabrielhl @cjhowald @xonic @dami-gg WDYT?

**Comment by dami-gg** [comment]
I agree with using the double dash but what about if we also add the "is" keyword as we do for hidden, shown, etc...? i.e. dc--is-text-right
