### ISSUE TITLE
feat(demo): add patterns page

### ISSUE THREAD

**Issue by rbarilani** [zalando/dress-code#178]
Add patterns page under core section.

depends on #177

**Comment by gabrielhl** [comment]
Please clarify what this is? UX patterns?

**Comment by rbarilani** [comment]
@gabrielhl Hey. Yup.

This is about creating a section/page demonstrating the usage of selectors contained in the [patterns module](https://github.com/zalando/dress-code/blob/develop/src/styles/core/_patterns.scss).

Maybe it would also make sense to rename ```_patterns.scss``` to ```_utilities.scss``` to use a word that sounds more familiar to css framework users.

**Comment by gabrielhl** [comment]
Yes, also because in a styleguide/pattern library context, pattern can mean commonly used interface patterns so it's confusing
