### ISSUE TITLE
docs(description): change the description

### ISSUE THREAD

**Issue by rbarilani** [zalando/dress-code#183]
Change the description without mentioning Brand Solutions (I also suggest to change Framework to Library and to mention BEM and atomic design).

updates:

- github repo settings
- README.md
- demo index
- package.json (in this file it make sense also to update the keywords... BEM, atomic design, css library, etc., remove zalando also here)
- bower.json

**Comment by sambhav-gore** [comment]
Fixed in https://github.com/zalando/dress-code/pull/213
