### ISSUE TITLE
What if... PHANTOM CSS? (visual regression testing)

### ISSUE THREAD

**Issue by rbarilani** [zalando/dress-code#185]
I would really like to setup visual testing to prevent regression. 

I great article about visual testing: https://css-tricks.com/visual-regression-testing-with-phantomcss/

@alexisinwork @mrac Can you help us on this one?

**Comment by cjhowald** [comment]
Philippe Clement implemented this for the shop frontend. He might be able to help us, or at least provide advice and guidance.

**Comment by rbarilani** [comment]
@cjhowald good to know. Can you contact Philippe and maybe set up a fast workshop about this topic?

**Comment by cjhowald** [comment]
I'm on it.

**Comment by LeoAref** [comment]
@cjhowald @rbarilani What's the current status of this issue?
I can work on it.

**Comment by cjhowald** [comment]
@LeoAref I discussed this with Philippe Clement back in April, but it appeared to be a significant effort and it was skipped in favor of more pressing issues.

**Comment by LeoAref** [comment]
@cjhowald So, I can start working on it but don't give it the priority

**Comment by cjhowald** [comment]
@LeoAref Yeah, go for it.

**Comment by gabrielhl** [comment]
@LeoAref do you think this is feasible or you're working on it? Otherwise let's close it and keep it as a future plan.

**Comment by LeoAref** [comment]
@gabrielhl I didn't start working on it yet!
We can close it, but I see that it's feasible...

**Comment by mroderick** [comment]
This doesn't look like it is going to happen anytime soon, can we close it?

**Comment by rbarilani** [comment]
@mroderick actually we are working on it here: https://github.com/zalando/dress-code/pull/412

**Comment by rbarilani** [comment]
closed via #412 

extended/split in #424 #423
