### ISSUE TITLE
Define a bigger standard element height for touch

### ISSUE THREAD

**Issue by gabrielhl** [zalando/dress-code#188]
Our most common atoms (button, form elements, etc) all have a height of 36px. That is acceptable for desktop but all responsive and mobile guidelines recommend 44px or 48px as a minimum. Should/could we define this in the dress code so that all applications inherit it?

**Comment by LappleApple** [comment]
Hi @sambhav-gore @gabrielhl, This issue dates back to April 2016. Do you still want to do it? If not, let's close? Or if you want help, let's add a "Help Wanted" tag. cc @alexkops

**Comment by rbarilani** [comment]
@dami-gg To don't introduce breaking change I would suggest to add a modifier or put this one in a 3.0.0 milestone

**Comment by dami-gg** [comment]
@rbarilani valid point Anyway I don't think this is among the most urgent things to work on right now
