### ISSUE TITLE
dc-toast shows black border when animated

### ISSUE THREAD

**Issue by dami-gg** [zalando/dress-code#191]
When using it with an animation to slide-in/slide-out the dc-toast shows an empty box with black border after the for example green box of the success toast is hidden.

This can be fixed applying the border style only to the success, error, etc... types like this:

.dc-toast__content {
  border-style: none;

  &--success,
  &--info,
  &--warning,
  &--error {
    border-style: solid;
  }
}

@gabrielhl You can check this broken behaviour on the development and stage environments of the Solution Center when deleting a user for instance.

**Comment by gabrielhl** [comment]
@dami-gg I've tried but can't see this. What browser are you using

**Comment by dami-gg** [comment]
We've already implemented the fix so it was too late now :)
