### ISSUE TITLE
dc-select line-height in chrome

### ISSUE THREAD

**Issue by izabelabratovic** [zalando/dress-code#195]
![Image of the issue]
(http://i.imgur.com/lUByKtV.png?1)

The line-height for <select> element is insufficient in Chrome/Chromium and Safari, it cuts off the bottom of the letters, see image (Optiong 1)

**Comment by gabrielhl** [comment]
@izabelabratovic can you pull the topic/select-atom-improvement-187-189 and see if it fixes it for you (it does for me, but might be an OS difference)

**Comment by sambhav-gore** [comment]
Fix in https://github.com/zalando/dress-code/commit/e55046e8f9d0d453e0e95667ef05d70a0217ffcf
