### ISSUE TITLE
Add delete icon

### ISSUE THREAD

**Issue by gloriarupprecht** [zalando/dress-code#200]
Please add this icon called 'clear' to the dress-code.
[clear icon](https://github.com/zalando/dress-code/files/293588/delete.icon.copy.svg.zip)
*Usage*
After doing a search via search text field, this icon should show up in the search input field instead of the magnifying glass.

**Comment by gabrielhl** [comment]
The behavior (changing when text is entered) is not possible to have without javascript. But we can create a class for it and simulate the demo for the demo.
