### ISSUE TITLE
Font files versions

### ISSUE THREAD

**Issue by mrac** [zalando/dress-code#203]
We had issues with unmatching icons, when switching from one app (using dresscode ver.1.2) to another app (using dresscode ver.2.0). Font files has been cached by first app but it was incompatible in second app.

Probably postfixing the font files by a version name would be a good idea.

**Comment by rbarilani** [comment]
Hi @mrac,

> ...when switching from one app (using dresscode ver.1.2) to another app (using dresscode ver.2.0). Font files has been cached by first app but it was incompatible in second app.

We are sorry but we can't solve that problem... if you have two apps serving different versions of dress-code they also have to to serve different versions of the font (from different locations).
If you are using the SASS version,  you can customize the font-path, by using the variable ```$dc-font-path```. 

So let's imagine that you use a CDN to host the fonts:

https://mycdn.com/fonts/1.2.0/DressCodeIcons.ttf
https://mycdn.com/fonts/2.0.0/DressCodeIcons.ttf

Then in SASS... app using 1.2.0
```
$dc-font-path: https://mycdn.com/fonts/1.2.0
```

app using 2.0.0

```
$dc-font-path: https://mycdn.com/fonts/2.0.0
```

P.S. right now we are working on the cache busting support when a new version is released but we will not change the font filenames, we will append a query string as (for example) [octicons](https://github.com/primer/octicons/blob/master/build/font/_octicons.scss) does.

@mrac Does it make sense?

**Comment by mrac** [comment]
@rbarilani Assuming we have 2 apps using different versions of dresscode (and thus different fonts). If we access app-1 as first, the fonts-version-1 will be loaded and cached. And then when we access app-2, fonts-version-2 will NOT be loaded. Because the font file is cached, fonts-version-1 will be still displayed, and because those may not be compatible, the icons will be broken.

I think, having a version number in the font file would solve that problem.
