### ISSUE TITLE
Make table responsiveness optional

### ISSUE THREAD

**Issue by sambhav-gore** [zalando/dress-code#222]
As of now the table is responsive all the time which should be made optional as normally tabular data needs sorting, and in the current card layout (on smaller screen sizes) though it looks good, it doesn't really look like a tabular data.
I suggest having this behaviour of table turning to card-layout optional. And by default the table will be shown with scroll bars on smaller screen (whenever required).

**Comment by gabrielhl** [comment]
Hey @sambhav-gore I've just pushed a branch with a suggestion for this. I don't like that it's very verbose: the variant --responsive has to be added to every level of the table. I would think it would be better to just enable/disable the whole thing on the table, but not sure if that is possible with the modular architecture that DC has. Maybe @rbarilani has an idea or input?

**Comment by sambhav-gore** [comment]
Hi @gabrielhl I like the idea of having  --responsive to the entire table as well. you can achieve it in the current architecture by passing a selector and applying the responsive specific styles to the child selector only when desired:

```scss
    @mixin dc-table {
       /* normal stuff */;
    }

    @mixin dc-table--responsive ( $tr-selector: ".dc-table__tr" ) {
       #{$tr-selector} {
           /* only the styles you want when tr is within dc-table--responsive */ 
           /* you may also loop through the break points here and include the media queries */
        }
    }
    /* Later .. */
    .dc-table {
        @include dc-table;
    }

    .dc-table--responsive {
        @include dc-table--responsive;
    }
```

This will output in 

```css
    .dc-table {
        //normal stuff
    }

    .dc-table--responsive .dc-table_tr {
        //only specific to tr within reponsive modifier
    }
```

This does create a nesting but for table level I think it is okay, as we are not hard coding the class names and rather passing the tr class name to the mixin. Someone else using only the mixins (scss) can pass a different class name for tr selectors if required. 
@rbarilani wdyt ?

**Comment by rbarilani** [comment]
@sambhav-gore I think it's a compromise that we can take.
So go for it!

One question: how this does it play with this open PR #246?

**Comment by gabrielhl** [comment]
TODO: Update with @sambhav-gore suggestion, mergin with the recent develop branch that includes #246
