### ISSUE TITLE
Different height of input and selectbox

### ISSUE THREAD

**Issue by Nagogus** [zalando/dress-code#225]
is it expected design that select box and input field heights are different?
Version: 2.0.0-beta
Code: 
```
<input class="dc-input " id="searchOnlyText" type="search" placeholder="Search..."/>
<select class="dc-select">
  <option value="some">Option</option>
</select>
```

Result:
![Image of the issue]
(http://i.imgur.com/G8oQbin.png)

Should it be like that?

**Comment by gabrielhl** [comment]
No, it shouldn't. In the demo everything is aligning. Let's investigate why on your app it's breaking.
![image](https://cloud.githubusercontent.com/assets/31034/16613446/6bea5cb0-436c-11e6-9a5a-336a08e46197.png)

**Comment by Nagogus** [comment]
Sorry, false alarm, I was using alpha, it is fixed by `line-height` change in beta.

**Comment by sambhav-gore** [comment]
This is now surely broken.

The height for select is smaller now.


<img width="283" alt="screen shot 2016-10-04 at 12 44 55" src="https://cloud.githubusercontent.com/assets/11697969/19071468/8c927ec4-8a30-11e6-8f40-e9e39540c1b8.png">
