### ISSUE TITLE
How to use toast animation

### ISSUE THREAD

**Issue by bzums** [zalando/dress-code#227]
Hey,
in the toast description it says that there are animations "built in" and i am wondering how to use/trigger them because without any further config it seems not to work (and that is stated as well in the explanation: "Note: the animation duration is not defined by the dress code and must be passed by you."). How to use/trigger the animations for Toasts/other components, are there any examples?

Best

**Comment by gregdeane** [comment]
Not a pro at dress code but maybe put something like this in your scss file:

```css
.dc-toast--top {
  animation-duration: 4s;
}
```

**Comment by bzums** [comment]
yeah ok that was simple, thanks ;)
