### ISSUE TITLE
Support and Demo putting inputs and inputGroups in table and/or grid

### ISSUE THREAD

**Issue by sambhav-gore** [zalando/dress-code#228]
At the moment, it is somewhat difficult to create a form which has inputs in a table (or perhaps a grid). 

DC should have the necessary styles to support adding inputs and input groups within a table/grid based layout. 

A demo for the same should also be created.

**Comment by gabrielhl** [comment]
@sambhav-gore what do you mean by somewhat difficult? Could you be more specific about the difficulties?

**Comment by sambhav-gore** [comment]
@gabrielhl Main issue is with the input-group as it doesn't specify the flex property for input which is within the group. As a result if we try to create a grid based layout with multiple input groups it doesn't align correctly. Solution would be to allow specifying a width to the group (100% when within a column) and make sure that it aligns correctly.

**Comment by frontendherodk** [comment]
@sambhav-gore Please have a look at this again

**Comment by sambhav-gore** [comment]
@frontendherodk I am unable to reproduce this now. I am closing this for now.
