### ISSUE TITLE
Replacing font urls from http to https

### ISSUE THREAD

**Issue by frontendherodk** [zalando/dress-code#231]
At the moment in the demo of dress code, under typography, there is a section "Get the font"
Currently that's a link tag with a http link, we should consider using https. 

Additional, Google Font's also support import statements directly in SASS files, we could add that as an option as well. 

Like the following
`
@import 'https://fonts.googleapis.com/css?family=Roboto:300,500';
`

**Comment by sambhav-gore** [comment]
@frontendherodk AFAIK google's font api supports both protocols http and https, so ideally the link should be just as follows (no scheme/protocol):
```
<link href="//fonts.googleapis.com/css?family=Ubuntu:300,500" rel="stylesheet" type="text/css">
```

**Comment by gabrielhl** [comment]
I forgot to mention it but #240 closes this.
