### ISSUE TITLE
Add vertical/horizontal tab to dress code

### ISSUE THREAD

**Issue by ashwinaggarwal** [zalando/dress-code#238]
Sometimes a number of charts or lists are to be shown to user, but user doesn't view them simultaneously. These view may or may not share context.

Dress code should have vertical/horizontal tab css to show tab component as below.

<img width="1079" alt="screen shot 2016-08-15 at 18 04 45" src="https://cloud.githubusercontent.com/assets/5618454/17670557/debcbda8-6312-11e6-988c-60d838af4b54.png">

<img width="1071" alt="screen shot 2016-08-15 at 18 04 55" src="https://cloud.githubusercontent.com/assets/5618454/17670561/e0f0ae40-6312-11e6-8fca-3239e2968895.png">

<img width="1168" alt="screen shot 2016-08-15 at 18 05 13" src="https://cloud.githubusercontent.com/assets/5618454/17670569/e3083054-6312-11e6-830f-2e5dac138416.png">

**Comment by LeoAref** [comment]
@gabrielhl What's the status of this?
I can work on it if we agreed about it, I think it's nice to have

**Comment by LeoAref** [comment]
@ashwinaggarwal Great, so just discuss it with @gabrielhl to proceed

**Comment by gabrielhl** [comment]
Hi, I agree you can push something like this. I have some modifications on the design, as we don't use light orange backgrounds such as you have. You can create a branch and I can collaborate with you directly on it, or I can enter here some images to illustrate what should be changed. Let me know what's more confortable for you ;)

**Comment by gabrielhl** [comment]
@ashwinaggarwal Please tell us if you still have something to push for this issue. For now I'm tagging it as help wanted if other people would like to contribute.

**Comment by ashwinaggarwal** [comment]
@gabrielhl I have the code for the tabs as shown in screenshots above, it would be better if you can share a picture from UX on how the real component should look with dresscode styles and I will style is accordingly.

**Comment by bzums** [comment]
@ashwinaggarwal @gabrielhl 
I just wanted to ask what the status of this issue is? We are also very interested in tabs :) 👍

**Comment by gabrielhl** [comment]
@ashwinaggarwal Just remove the orange background. You can keep the orange "active" bar. Then open a PR and we'll review
