### ISSUE TITLE
Convert all media queries to the grid sizes

### ISSUE THREAD

**Issue by gabrielhl** [zalando/dress-code#239]
We currently have two breakpoint systems being used, one for the grid, one "legacy". To simplify usage we should migrate all legacy MQs to the grid break points.

**Comment by rbarilani** [comment]
@gabrielhl Can we also remove ```breakpoint```usage plain css media queries?
So we can remove the *annoying* breakpoint dep to simplify getting started. (ps. we can still use it but just for the demo as devDep)
WDYT?

**Comment by gabrielhl** [comment]
@rbarilani could be replaced by simple variables e.g. 
`@media (min-width: $breakpoint-small)`

**Comment by rbarilani** [comment]
@gabrielhl Yep exactly...
