### ISSUE TITLE
Bake some SVG optimization into gulp tasks

### ISSUE THREAD

**Issue by gabrielhl** [zalando/dress-code#256]
Just like we have scss lint, we could use some automatic optimization of our svgs (at least for cleaning up extra cruft). Something like https://www.npmjs.com/package/gulp-svgo.
@rbarilani @sambhav-gore WDYT?

**Comment by LappleApple** [comment]
Hey, is this issue still open?

**Comment by gabrielhl** [comment]
It was open as a discussion research, but we have other priorities. So I'm closing it.
