### ISSUE TITLE
Select field arrow position depends on the width

### ISSUE THREAD

**Issue by LeoAref** [zalando/dress-code#259]
The select field background arrow position depends on the width of the field _"longest option"_, and this makes inconsistency in the select fields looking.

### Current background style:
```
url(data:image/...) no-repeat 92% 50% #fff
```

### Examples:
![screen shot 2016-09-30 at 13 11 30](https://cloud.githubusercontent.com/assets/6577222/18990015/8ff775c0-870f-11e6-8b9a-674b95a992b6.png)

![screen shot 2016-09-30 at 13 11 55](https://cloud.githubusercontent.com/assets/6577222/18990018/9563877e-870f-11e6-801b-0e68e5543931.png)

**Comment by Nagogus** [comment]
I think @sambhav-gore has fixed it once

**Comment by LeoAref** [comment]
@Nagogus Yes, here #232
