### ISSUE TITLE
Change approval process

### ISSUE THREAD

**Issue by dami-gg** [zalando/dress-code#273]
As agreed in today's meeting between UX + Norris frontend devs we will switch to a new approval system where two approvals, one from UX and one from an engineer are needed in order to be able to merge a PR.

We need to adjust both the repository configuration and the Zappr config file in order to allow this.

**Comment by dami-gg** [comment]
I'm setting up a UX-brand-solutions group but I can't add you @gabrielhl @xonic @grupprecht there yet since you're not part of the Zalando organization in GitHub You need to fill the form to be added to it by Lauri. I bet @frontendherodk can provide you the link ;)

Please let me know when at least one of you has done that so I can proceed with the rest of this task

**Comment by gabrielhl** [comment]
There's me and @xonic there now. You can proceed @dami-gg

**Comment by gabrielhl** [comment]
Can we close this?

**Comment by gregdeane** [comment]
Closing since it's been implemented. Also, #306 actually reverses these changes.
