### ISSUE TITLE
Add "loading" state for the dialog molecule

### ISSUE THREAD

**Issue by LeoAref** [zalando/dress-code#276]
Most probably we will have to call endpoint before closing the dialog, like validating the username/password, etc

So I think it'll be helpful to have "loading" state for the dialog like this, that blocks the user from submitting again or closing the dialog (we can make the closing optional, by adding/removing the close button like what I have here 👇)

![screen shot 2016-11-08 at 09 59 51](https://cloud.githubusercontent.com/assets/6577222/20093878/0166336a-a59f-11e6-8c2a-5e30a58d9e67.png)

-----

#### Todo:
- [ ] Add new state `blocked` to the dialog
- [ ] Supports displaying **loading** and **text+button**

**Comment by LeoAref** [comment]
@gabrielhl what do you think?

**Comment by gabrielhl** [comment]
I would rather not have a specific `dialog--loading` because it's not reusable for other situations we haven't thought of yet. I would say something general like `dialog--blocked`, where you disabled mouse interaction on the dialog, and using the default loader on top of it.

**Comment by LeoAref** [comment]
@gabrielhl So you mean something like this screenshot, and just change the state class from `dialog--loading` to `dialog--blocked`, right?

**Comment by gabrielhl** [comment]
Yes, something like that.

**Comment by gabrielhl** [comment]
@LeoAref Update on this?

**Comment by LeoAref** [comment]
@gabrielhl I did some progress in it, but it's not finished yet
I'll continue working on it this week

**Comment by LeoAref** [comment]
I didn't have time to finish this, I'll try to finish it soon!

**Comment by dami-gg** [comment]
@LeoAref do you think you can still take care of this or someone else should?

**Comment by rbarilani** [comment]
@LeoAref IHMO this is really to specific.... what we can is reusing `dc-overlay` 

Something along those lines:

```html
<div class="dc-overlay dc-overlay--opposite"></div>
```

> `dc-overlay--opposite` is white instead of being black
