### ISSUE TITLE
Remove develop branch

### ISSUE THREAD

**Issue by frontendherodk** [zalando/dress-code#280]
We should stick to having master as the single source.

**Comment by rbarilani** [comment]
@frontendherodk If you are gonna use pure Github Flow remmeber to change the contributing guidelines.

**Comment by gregdeane** [comment]
Remember to updated [`README.md`](https://github.com/zalando/dress-code/blob/develop/README.md) and [`RELEASING.md`](https://github.com/zalando/dress-code/blob/develop/docs/guides/RELEASING.md) when the develop branch is removed.

**Comment by gabrielhl** [comment]
@gregdeane @cjhowald it seems the develop branch is gone. Can this one be closed?

**Comment by gregdeane** [comment]
@gabrielhl Not quite yet. A PR needs to be opened with all documentation updated to reflect the removal of `develop`. Thx!

**Comment by gabrielhl** [comment]
This is taking too long. Someone has to do this. @frontendherodk how about you?

**Comment by cjhowald** [comment]
I am on it.
