### ISSUE TITLE
in normalize.scss input[type="search"] has box-sizing of content-box which creates an issue when trying to place a search field on a page

### ISSUE THREAD

**Issue by sambhav-gore** [zalando/dress-code#286]
In normalize.scss, input[type="search"] has box-sizing of `content-box`

This creates an issue if trying to place a search field within a table a cell. 

This is a minor issue but it would be best if we default it to `border-box` and use `content-box` only within `dc` styles.

**Comment by gabrielhl** [comment]
@sambhav-gore Shouldn't it be the opposite? We shouldn't touch normalize, but rather implement the box-sizing we want directly in dc? 
Related read: https://github.com/necolas/normalize.css/issues/202

**Comment by sambhav-gore** [comment]
@gabrielhl  In a way yes. but as it is specified right now, it doesn't work. `input[type=search]` in normalize, VS `.dc-input`. Former is more specific so .dc-input does not override the border-sizing for input[type=search]

What I want to ask is why is it default to `content-box` within dc-normalize whereas input=text is using border-box. 
These two are identical form fields with two different border-box values in DC. 
I agree that it is taken from a third-party lib, but we should make changes into it if it makes sense.
In your linked library (above comment) there is an argument that someone who wants to use border-box can easily override, Same argument applies to `content-box` value as well. What I want to get from a library is consistency. 

Other solution would be to have a more specific selector in dc for `input[type=search].dc-input` and apply border-box box-sizing there.

**Comment by rbarilani** [comment]
@sambhav-gore what about ... to don't introduce breaking changes:
using a modifier class ```.dc-input--search```

##### Style (something like this....)

```css
input[type=search].dc-input--search {
}
```

##### Usage

```html
<input type="search" class="dc-input dc-input--search" />
```
