### ISSUE TITLE
Enhancement request: Add utility classes for responsive behaviour

### ISSUE THREAD

**Issue by sambhav-gore** [zalando/dress-code#287]
It will be helpful if some helper utility classes (for responsiveness) are added, something as follows:

- hide-for-medium-up (hides the element for screen sizes 'medium width' and up)
- show-for-large-down (shows the element only for screen sizes of large width and below).

Something to keep in mind (WHEN possible) while writing the styles the default should always consider smallest possible screen sizes first (mobile-first-approach), the modifiers should only modify the behaviour for targeted screen-sizes and up.

**Comment by gabrielhl** [comment]
@sambhav-gore I've got a 1st version. I have one issue with it is that to target a specific size only (e.g hide only for medium) you have to use two classes (one hide from, one show from). Maybe we should have classes that target one specific size? e.g. dc-hide-for-medium

**Comment by sambhav-gore** [comment]
@gabrielhl I like the idea of targeting specific size as well.
