### ISSUE TITLE
Switch to yarn?

### ISSUE THREAD

**Issue by cjhowald** [zalando/dress-code#288]
Some of us have been using yarn over npm, and a yarn.lock has made its way into the repo. We should decide if we want to encourage contributors to use yarn instead of npm, including updating the yarn.lock when package.json changes.

**Comment by gregdeane** [comment]
My PR #281 is when yarn.lock was introduced. Since it's faster than `npm` and easy to update (it updates automatically), it's probably a good idea to encourage its use.

Just my two cents...

**Comment by rbarilani** [comment]
@cjhowald @gregdeane If we have a yarn.lock, we should add YARN as a contributors requirement in the Contributing section and point out that the usage of YARN is mandatory.

**Comment by gregdeane** [comment]
@rbarilani I can't recall specifically what we agreed to on Friday but does it have to be mandatory? Of course, we should encourage its use but even if someone used `npm install`, the next dev to come along and use `yarn` should get the updated file.

@cjhowald @frontendherodk What do you guys think?

**Comment by frontendherodk** [comment]
I don't see any drawbacks to using yarn so I would just go ahead and add it. Not sure if we have a way of actually checking if they used it or not.

**Comment by cjhowald** [comment]
It only really matters if someone changes a dependency, then `yarn.lock` needs to be updated alongside `package.json` (yarn does this automatically). We can enforce this in PRs.

**Comment by cjhowald** [comment]
That said, I'm okay just telling contributors to use `yarn`.

**Comment by gregdeane** [comment]
Added label `docs` to this issue to use it for the PR.
