### ISSUE TITLE
.dc-h3 has the wrong font-size in code

### ISSUE THREAD

**Issue by gabrielhl** [zalando/dress-code#289]
The `font-size` for `dc-h3` currently has a value of `1.8rem;`. This is wrong. It should be `2.2rem`, according to the demo and our mockups. Likely a copy-paste issue from `dc-h4`.

**Comment by gregdeane** [comment]
Here's the offending line: https://github.com/zalando/dress-code/blob/develop/src/styles/core/_typography.scss#L183

**Comment by gabrielhl** [comment]
I took the opportunity from fixing this to separate the typography section into various files, so that the demo code is separately shown for each one. It makes it more usable.

**Comment by gregdeane** [comment]
@gabrielhl Thanks for all your work on these issues.
