### ISSUE TITLE
Release 2.0.0-beta.1

### ISSUE THREAD

**Issue by gregdeane** [zalando/dress-code#292]
We need to make an "interim" release that is not an official milestone. We are thinking to call it version 0.9. This indicates that a) it's not the truly official 1.0 release and b) 2.0 is not the appropriate number for an official release. 1.0 should be the official release since we are moving out of beta.

@gabrielhl @sambhav-gore @rbarilani What do you think?

**Comment by rbarilani** [comment]
@gregdeane can we have 2.0.0-beta.1? Like for example Angular does? https://github.com/angular/angular/releases

**Comment by gregdeane** [comment]
@rbarilani that works for me. I spoke to @sambhav-gore and he agreed with you. If @frontendherodk agrees, let's do it.

**Comment by frontendherodk** [comment]
@rbarilani Why are we starting with 2.0.0 and 1.0.0-beta?
