### ISSUE TITLE
Update RELEASING.md

### ISSUE THREAD

**Issue by gregdeane** [zalando/dress-code#293]
What: A new "Step 2" needs to be added.
Why: The step for merging the release branch into `develop` is missing.

Text:

"**2) A release branch will be created and pushed automatically. Open a PR from the release branch to `develop`.**"

All steps following the addition remain but the step numbers increase by 1.

This new step will need to be removed once the `develop` branch is deleted.

**Comment by rbarilani** [comment]
@gregdeane let's redefine our release process, automate what we can automated (as you suggested) and discuss when we should build the distribution files.
