### ISSUE TITLE
Tooltip doesn't support buttons inside

### ISSUE THREAD

**Issue by uxsasha** [zalando/dress-code#301]
![state 1](https://cloud.githubusercontent.com/assets/23312993/21046661/fe3c1996-be05-11e6-8083-b4ba3eaf5660.png)

We need to be able to add a button inside of the content of a tooltip. Currently this is not possible.

**Comment by LeoAref** [comment]
I'll be working on this issue

**Comment by gabrielhl** [comment]
@LeoAref I think guys from the CMS already have a solution. Might be worth checking with @uxsasha first

**Comment by gabrielhl** [comment]
@LeoAref Any news here?

**Comment by dami-gg** [comment]
@LeoAref do you have any progress on this or shall anyone else work on it from scratch?

**Comment by dami-gg** [comment]
After talking with @sambhav-gore and also seen that @rbarilani disagreed with this idea we have decided not to support this component in Dress Code
