### ISSUE TITLE
Remove zappr requirement for UX approval

### ISSUE THREAD

**Issue by gregdeane** [zalando/dress-code#306]
There are times where the code is strictly technical (config, releases, scripts, etc.) where a mandatory UX approval is unnecessary. In terms of release, this may be a bottleneck which we cannot afford.

Let's remove the mandatory UX approval from zappr config.

@gabrielhl As a team, we agree to wait for your approval on any sass/ux-related changes. We won't merge unless you have given the go ahead. But we will remove the mandatory approval so that we can proceed more quickly in cases of strictly-technical updates.

**Comment by gabrielhl** [comment]
Super late to the party, but totally agree
