### ISSUE TITLE
Color Palette comparison with Material Palette

### ISSUE THREAD

**Issue by pdjota** [zalando/dress-code#308]
Taking a look at Material color palettes (https://material.io/guidelines/style/color.html#color-color-palette) comparing it with DressCode palette it delivers less colors, DC colors ranging from 80 to 10 are much darker. What is the deal with opacity and the range? DC seems less vivid options.

**Comment by rbarilani** [comment]
@gabrielhl @xonic ping

**Comment by gabrielhl** [comment]
Hi @pdjota as Dress Code started as style-opinionated, B2B focused framework, our colors are indeed less numerous and less bright than something like Material which is more general. We'll look into this. I'd be interested in knowing what your intended use case is.

**Comment by xonic** [comment]
Sorry for the late reply.
Thanks for your input @pdjota, I'd also be interested if you actually already had limitations due to DC usage and color palette.

**Comment by gabrielhl** [comment]
Closing this discussion for now as the initial commenter hasn't responded.
