### ISSUE TITLE
Add a secondary divider

### ISSUE THREAD

**Issue by LeoAref** [zalando/dress-code#310]
Add a secondary divider in with `$dc-gray70` / `#ededed` color

**Comment by gregdeane** [comment]
@LeoAref Please feel free to submit a PR. Thx!

**Comment by LeoAref** [comment]
@gregdeane Will do 😊

**Comment by gabrielhl** [comment]
@LeoAref It's actually $dc-gray70 // #ededed. I wrote down the wrong color on the doc.
