### ISSUE TITLE
Height discrepancy for some inputs

### ISSUE THREAD

**Issue by cjhowald** [zalando/dress-code#323]
Some of the dress code inputs have a height of 22px. They should be 24px instead.

- dc-select--small
- dc-checkbox (note: dc-checkbox--alt is already 24px line height)
- dc-radio
- dc-btn--small

Also check the following, which might need to change to match:
- dc-list__title

**Comment by cjhowald** [comment]
@xonic here is the issue we discovered today.

**Comment by gabrielhl** [comment]
Good work, thanks for noticing this!

**Comment by gabrielhl** [comment]
I'm working on this. For now my approach will be to make the elements have a 24px height but keep the checkbox/radio/etc having 22px to not impact the UI visual.

**Comment by xonic** [comment]
<img width="205" alt="screen shot 2017-02-15 at 16 00 14" src="https://cloud.githubusercontent.com/assets/133157/22979786/d872ec7c-f397-11e6-8abd-6632df281ae1.png">

**Comment by gabrielhl** [comment]
Tracking my progress
[ ] dc-select--small
[ ] dc-checkbox
[ ] dc-radio
[ ] dc-btn--small
[ ] dc-list__title

**Comment by gabrielhl** [comment]
Change the title to make it clearer that this is related to the element's height, not line height
