### ISSUE TITLE
convert classes to follow BEM syntax

### ISSUE THREAD

**Issue by frontendherodk** [zalando/dress-code#342]
We should leave the old classes for some time before we deprecate them

**Comment by frontendherodk** [comment]
dc--text-left -> dc-text--left
dc--text-center -> dc-text--center
dc--text-right -> dc-text--right

dc--text-less-important -> dc-text--less-important
dc--text-small -> dc-text--small
dc--text-success -> dc-text--success 
dc--text-error -> dc-text--error
dc--text-truncate -> dc-text--truncate

**Comment by gabrielhl** [comment]
@frontendherodk I think the idea of `dc--` classes is that they are utilities that can be used on any element and not only on `dc-text` maybe @rbarilani can explain. But I agree then the name could be more clear like `dc--u--text-left`?

**Comment by frontendherodk** [comment]
@gabrielhl I understand that they are utility classes but it seems like dc is a container for everything then. The functionality of the classes stays the same but I think it's more clear from a BEM perspective what the classes actually do. 

If that's, not the cases I would suggest something more like `align-left`

**Comment by rbarilani** [comment]
@frontendherodk Yep now I remember what was the decision here.
By following BEM syntax when you use -- it means that you add a modifier to a block, `dc-text` doesn't exist as a block. So the decision was using `<namespace>--<modifier>`

**Comment by frontendherodk** [comment]
But does `dc` exist as a block?

**Comment by rbarilani** [comment]
@frontendherodk `dc` it's just a namespace to don't collide with others frameworks.

**Comment by frontendherodk** [comment]
Ah sorry. Missed that part. 

I get the argument though I still find it a bit misleading. But if that's the consensus then we'll stick with it :)

**Comment by rbarilani** [comment]
I would stick to the current one. That's my vote.

**Comment by SergKam** [comment]
I would stick to the current one.
From this logic <namespace>-<block>--<modifier>  it is better
dc--text-small >>dc---text-small 
But I dont like it :)

**Comment by frontendherodk** [comment]
Yeah that's the thing. when you see `dc--` you assume dc is a block. 

You can read about namespacing is this article: https://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/

**Comment by dami-gg** [comment]
Please @frontendherodk check if this still makes sense and we need to work on it as part of the new milestone or can be closed/postponed/rediscussed?

**Comment by frontendherodk** [comment]
Seems like people want to stick to what we have so I'll close this one.
