### ISSUE TITLE
chore(bower): drop bower support

### ISSUE THREAD

**Issue by rbarilani** [zalando/dress-code#346]
Drop bower support.
Remove bower.json and update documentation where bower is mentioned.

**Comment by rbarilani** [comment]
@LappleApple just remind me also to archive/delete https://github.com/zalando/dress-code-bower

**Comment by LappleApple** [comment]
@rbarilani I honestly don't know what your note means. Can you create the IT-Compliance ticket and then you'll have the reminder?

**Comment by rbarilani** [comment]
@LappleApple yep don't worry this was just to don't forget about that repo while resolving this issue.

**Comment by rbarilani** [comment]
ticket ref: https://techjira.zalando.net/browse/TGC-352
