### ISSUE TITLE
Add icons for loading status

### ISSUE THREAD

**Issue by Lapanti** [zalando/dress-code#350]
It would be so nice if the [icons](https://zalando.github.io/dress-code/03-atoms.html#icons) would include a loading-one as well (preferably with and without spinning), would this be possible?

**Comment by rbarilani** [comment]
@Lapanti Can't you use the spinner component for that? I'm curious about the use case....

**Comment by Lapanti** [comment]
very valid point, I didn't remember it's existence, the only question would be to have it in the same size but I guess I can manage. The use case would in this case be having an icon that changes dynamically depending on the situation: "failure", "loading" and "success"

**Comment by rbarilani** [comment]
@Lapanti Ok I see.... I don't konw if we will provide something like that we should discuss it with the designer and I don't know if it's technically possible to have an animated font icon... BTW for sizing you can have your own modifier...

**Comment by Lapanti** [comment]
yes I know I can modify the size, but it will also lose the semantics in this case, and thus at least a non-spinning icon would be valid in my opinion

**Comment by rbarilani** [comment]
@peter-lowe ping.

**Comment by peter-lowe** [comment]
Yes - we should use the loading spinner we already have - do you have a screen shot of the context in which you need it?

**Comment by Lapanti** [comment]
I can add a gif of the use case in a bit

**Comment by Lapanti** [comment]
![dress-code-icons](https://cloud.githubusercontent.com/assets/2526798/25883165/1a3ad052-3551-11e7-809a-1f576487871c.gif) not sure if that managed, but basically it shows the status of elements I need to load over AJAX

**Comment by Lapanti** [comment]
Fontawesome has one: http://fontawesome.io/icon/spinner/
With the spinning for any icon: http://fontawesome.io/examples/
