### ISSUE TITLE
[Bug]: if dc-row is placed inside a flex container it takes the smallest possible size and breaks layout

### ISSUE THREAD

**Issue by sambhav-gore** [zalando/dress-code#354]
Issue Summary:

When a div which has `dc-row` applied to it is placed inside a flex container it takes the smallest possible size and breaks the layout. See screen shot below:

<img width="1028" alt="screen shot 2017-06-27 at 18 38 28" src="https://user-images.githubusercontent.com/11697969/27599095-dcc03cc0-5b67-11e7-8d59-715ab85cee85.png">

In the above image container is with blue background color. It is set to width 100% with `display:flex` and with some padding so we can see the alignment here.

Expected Result:

The row should be always taking a 100% space of container. Expected screen should look like the screenshot below:
<img width="1026" alt="screen shot 2017-06-27 at 18 40 57" src="https://user-images.githubusercontent.com/11697969/27599200-409c671e-5b68-11e7-8dac-1d41c0cc7a13.png">

The container is still `display:flex` but now the row takes 100% of its width.

### Possible Solution:
Just add `width: 100%` to `dc-row`. But we need to check if this the correct solution.

**Comment by sambhav-gore** [comment]
Upon further investigation I find that this will add further complexities. Just adding width:100% will not fix this issue as it will break lot of other things related to the placement of columns and gutters.

I propose to close this bug without any modifications with a note that it should be responsibility of the container to provide its own size correctly.

**Comment by rbarilani** [comment]
@sambhav-gore We will discuss this during our "radical focus" days.

**Comment by rbarilani** [comment]
Closed because it's the expected behaviour of flex model
