### ISSUE TITLE
chore(devDeps): update dev dependencies

### ISSUE THREAD

**Issue by rbarilani** [zalando/dress-code#359]
**As** A dress-code maintainer
**I Want** to use latest dev dependencies
**So That** I can take advantage of latest updates and bug-fixes

**As** A dress-code user
**I Want** see updated dev dependencies
**So That** I can rely on the project since is well maintained

**Acceptance Criteria**

- [ ] All gulp's task are working as before
- [ ] devDependencies badge is green

**Comment by sambhav-gore** [comment]
@rbarilani just realised if I do a clean install of npm packages I have to install webpack separately. Probably good if you can include webpack as a devDep as well (if not already done). Cheers!
