### ISSUE TITLE
dist folder is not available anymore for bower

### ISSUE THREAD

**Issue by xprommer** [zalando/dress-code#378]
You're referencing everywhere to dist folder in http://zalando.github.io/dress-code, but after dress-code installation via bower, there is no dist folder

**Comment by rbarilani** [comment]
Hi @xprommer, we actually drop "bower" support in the new versions.  Let's see somebody else want this back. If we forgot some "bower" instructions. please let us know. cheers.

**Comment by dami-gg** [comment]
Should we maybe state for some time in the repo that Bower support has been dropped?
