### ISSUE TITLE
Better documentation for font path and image path variables.

### ISSUE THREAD

**Issue by avb1989** [zalando/dress-code#388]
I was integration dress-code with a new angular4 app. The error was something like "File not found" because it was looking at the wrong directory. It took me a good long while yesterday to figure out the existence of "dc-font-path" and "dc-image-path" variables.

Maybe we can add them to the documentation (as part of FAQ) ?

**Comment by rbarilani** [comment]
@avb1989 Yeah! It will be great! Can you open a PR for that? 

> What about also adding a Scss Reference to the CORE section something like what we have already for the grid (http://zalando.github.io/dress-code/02-structure-and-grid.html#04-scss-reference)... WDYT?

Just drop a line if you need support. You can also find us [here on gitter](https://gitter.im/zalando-dress-code/Contributors)

**Comment by avb1989** [comment]
I'm not sure what you mean by SCSS reference. TBH I'm a bit new to the whole ecosystem. But I can definitely create a PR for the variables.

**Comment by rbarilani** [comment]
@avb1989 No problem. We will assist you in the process.

**Comment by dami-gg** [comment]
Merged
