### ISSUE TITLE
bug(icon): icon link is broken

### ISSUE THREAD

**Issue by rbarilani** [zalando/dress-code#405]
Icon link font is broken.

<img width="710" alt="screen shot 2017-11-16 at 12 53 25" src="https://user-images.githubusercontent.com/3602581/32889974-2d2365e6-cacd-11e7-865e-bd63fc6fa939.png">

Probably something went wrong during the release/font-generation. 

@xonic I think it can be that the SVG was exported without "degrouping" every shapes, convert to pathes and merge. WDYT?

**Comment by sambhav-gore** [comment]
This got resolved when I built again with all updated packages. 

It is deployed in the demo now and everything looks fine.

**Comment by esin-isik** [comment]
@rbarilani @sambhav-gore I understand I do not need to share the icons again with you. Is that correct?

**Comment by rbarilani** [comment]
We fix that issue but we would like to have the original sketch files and put them under version control
