### ISSUE TITLE
Request: tab header

### ISSUE THREAD

**Issue by fogfish** [zalando/dress-code#406]
You've made a cool enhancement with horizontal vertical tabs. I'd like to suggest you a "tab header" feature. Please example LAF. I've hacked it with `dc-tab__element--disabled` plus custom styles. It would be nice if library supports it.

<img width="1276" alt="screen shot 2017-11-17 at 18 50 46" src="https://user-images.githubusercontent.com/716093/32958952-ac7cfaf4-cbc8-11e7-9a3e-cd760f6cbcaa.png">

**Comment by dami-gg** [comment]
Hi, thanks for your feedback

We'd appreciate if you could open a PR with your proposition since you seem to have implemented it already seeing your screenshot. We can help and guide you in it if you need.

We want to encourage people to collaborate with Dress Code if they like it :)

**Comment by rbarilani** [comment]
@fogfish Hey, what is blocking you to contribute back? Dev Setup, Coding? Please, let us know you will help us to understand what can be improved to ease the contribution process.

**Comment by fogfish** [comment]
here you are!!!
