### ISSUE TITLE
docs(core): document all public Sass variables and mixins

### ISSUE THREAD

**Issue by sambhav-gore** [zalando/dress-code#407]
docs(core): document all public scss variables picking up the ones we think are required for customisation or extending.

**Comment by rbarilani** [comment]
@sambhav-gore I'm thinking about using this tool: http://sassdoc.com/

**Comment by rbarilani** [comment]
@dami-gg @sambhav-gore To have a unified sass reference using sassdoc and nicely integrated in our documentation site will take some time:

## Tasks

* Generate sassdoc by parsing scss file, integrated with gulp tasks: watch and build
* Implement custom templates to nicely display sass documentation in our website
* Integrate with the "live search"
* Add sassdoc comments and annotations to the scss source

So I will move this to 2.4.0
