### ISSUE TITLE
Avoid all caps at form labels 

### ISSUE THREAD

**Issue by fogfish** [zalando/dress-code#438]
I'd like to open a discussion about the design of form label `.dc-label` 

## Expected Behaviour

There are a few UX guidelines that recommend to avoid all caps

https://uxdesign.cc/design-better-forms-96fadca0f49c
https://blog.prototypr.io/all-caps-on-ui-good-or-bad-2570f14dc457
http://uxmovement.com/content/all-caps-hard-for-users-to-read/

I've notice a similar feedback from my users while using dress-code.
What do you think about a change of the style to remove all-caps constrains?
https://github.com/zalando/dress-code/blob/master/src/styles/atoms/_label.scss#L9  

## Actual Behavior

`.dc-label` uses all caps

**Comment by fogfish** [comment]
Any thoughts !?

**Comment by rbarilani** [comment]
@fogfish Can be changed or you can add a modifier.... are you able to open a PR for that?
