### ISSUE TITLE
Sass compilation fails after installing with npm

### ISSUE THREAD

**Issue by cjhowald** [zalando/dress-code#65]
This line in _base.scss is causing a compilation error after installing the dress code via npm:

```
@import "../../node_modules/normalize-css/normalize";
```

Steps to reproduce:
1. npm install dress code
2. run scss compilation (in central services, 'gulp styles')
3. compilation fails

The root issue is that _base.scss is assuming a particular structure of packages within node_modules, and that structure is not guaranteed. 

For now, I am working around this by just using the compiled css directly, but I would prefer to use standard sass importing.

**Comment by rbarilani** [comment]
@cjhowald Yep [NPM@3](https://github.com/npm/npm/releases/tag/v3.0.0) introduced flatten, deduped dependency by default... it seems there is not a clean way to handle non-JS third party dep with NPM@3. We are considering to put a version constraint for npm.
