### ISSUE TITLE
Improve Input Group

### ISSUE THREAD

**Issue by gabrielhl** [zalando/dress-code#72]
A basic input group exists in the price input. Let's improve it: 
- Accept any size of addon
- Accept left or right addon
- Can be used with other input than text (number, password, phone, etc)

**Comment by gabrielhl** [comment]
I just created a branch with a first version of this. The design is a little different than the previous one. This is because it doesn't seem possible to have an inoput-addon that is variable in size and in position while keeping it inside the input. We could fake this for the default state but not when the input is focused.

**Comment by rbarilani** [comment]
closed with #76
