### ISSUE TITLE
Create dropdown & dropup

### ISSUE THREAD

**Issue by gabrielhl** [zalando/dress-code#73]
Create a button that activate a dropdown or dropup.

**Comment by gabrielhl** [comment]
@rbarilani I did some dirty things there in the HTML to get a show/hide toggle. I can look into doing it with pure javascript or maybe we should include jquery in the fabricator page, just as an utility for the demo page but not a requirement for actually using the dress code css.

**Comment by gabrielhl** [comment]
Fixed the dirty stuff, demo js is now in its own file being pulled into f.js on demo.

**Comment by rbarilani** [comment]
@gabrielhl, can we close this one?
