### ISSUE TITLE
New Shiny Grid

### ISSUE THREAD

**Issue by rbarilani** [zalando/dress-code#80]
We have to came up with a shiny, super-simple grid, the one that we had is too complex and not really usable (will be removed). Maybe we can use directly the flex-box model.

**Comment by rbarilani** [comment]
@gabrielhl @cjhowald  can we consider to suggest or include the foundation grid as a dependency?
http://foundation.zurb.com/sites/docs/flex-grid.html

What do you think?

**Comment by cjhowald** [comment]
I am okay with it.

**Comment by gabrielhl** [comment]
It seems weird to me to be making a sort of framework but have another one as a dependency. But you're the developers :)

**Comment by rbarilani** [comment]
@gabrielhl Here the fact is that a grid system is not dependent to any brand solutions design... so implementing our grid is reinventing the wheel... 

"...It seems weird to me to be making a sort of framework but have another one as a dependency..."
I think the dress-code is not a framework... is more a library (it doesn't provide abstract components, it provides opinionated styled component).

**Comment by gabrielhl** [comment]
OK then!
