### ISSUE TITLE
Compiling SASS with Bower fails

### ISSUE THREAD

**Issue by cjhowald** [zalando/dress-code#82]
I pulled the library via Bower and added the toolkit import as directed in the README. The compile failed with errors until I made the following changes:

* **_import.scss:** ...normalize -> ...normalize.css
* **_btn.scss:** @extend .dc-cf -> @extend %dc-cf
* **_dropdown.scss:** @extend .dc-cf -> @extend %dc-cf

Please fix these changes in the base library if they are indeed bugs or advise on how to avoid these compile issues.

**Comment by rbarilani** [comment]
@cjhowald  Do you know which version and which type of sass compiler are you using?

**Comment by cjhowald** [comment]
Compass version 0.1.1 (latest)

**Comment by rbarilani** [comment]
@cjhowald Thanks. We will check compatibility issues. ASAP.
