### ISSUE TITLE
Improve tables

### ISSUE THREAD

**Issue by gabrielhl** [zalando/dress-code#90]
- [x] Add a way to modify internal (vertical) padding
- [x] Verify compatibility of dropdowns in tables
- [x] Verify compatibility of checkboxes and radios in tables
- [x] Verify compatibility of buttons (+dropdown/dropup) in tables

**Comment by gabrielhl** [comment]
Everything works, but there are issues caused by the default spacing in buttons, checkboxes and radios. 
How could we solve this while avoiding complicated BEM like dc-tooltip--in-table?

**How it behaves now**
![image](https://cloud.githubusercontent.com/assets/31034/13948448/588be7c8-f020-11e5-8989-1122be1456df.png)

**How it should behave**
![image](https://cloud.githubusercontent.com/assets/31034/13948435/46d1a0ea-f020-11e5-92dc-06024b917da7.png)

**Comment by gabrielhl** [comment]
@cjhowald @dami-gg What's your opinion on removing these default margins? Are you doing this already somewhere? Or would it break stuff for you?

**Comment by cjhowald** [comment]
We are overriding the style to remove the margin when needed (e.g. in a table). I think it makes sense to remove margins on atoms as it makes them more reusable. Molecules and higher-order structures should define spacing.

**Comment by xonic** [comment]
I had different approaches to this
* override styles when nested
* Have generic classes `space-lover`, `space-lover--large` that add different bottom margins on given elements. In our case I'd suggest `space-10`, `space-20`, etc. with one default (24px)
* A wrapper `<div class="space-lover">` around given elements
I usually combined number 2 and 3.

Also I suggest to use [single direction margins|http://csswizardry.com/2012/06/single-direction-margin-declarations/] for the sake of simplicity.
@gabrielhl @rbarilani @dami-gg @cjhowald WDYT?

**Comment by gabrielhl** [comment]
- We can't have override styles when nested because of the whole extreme BEM thing I think. 
- I like space-XX, because then each implementation can choose where to put it - directly on the element, on a container/wrapper, etc. It's the most modular/flexible approach.

And yes, for single direction margins, I think we already have it for almost everything. Maybe the spacer atom needs some fixing on that, it has a top margin I think.
