### ISSUE TITLE
Default cursor for buttons

### ISSUE THREAD

**Issue by dami-gg** [zalando/dress-code#91]
Shouldn't all buttons (dc-btn) have a cursor: pointer; by default?

Otherwise the property will likely need to be overridden in the projects using it

**Comment by rbarilani** [comment]
@dami-gg I suppose that using ```cursor: default``` is a design decision. @xonic  @gabrielhl Can you give me your opinion about that?

**Comment by xonic** [comment]
It's all about affordance. Form elements like buttons, select boxes, radio buttons, checkboxes, etc. all have strong affordances, users can tell they are interactive. 
On the other hand, elements with low affordance, such as links are supported by the changing cursor to clearly communicate they are interactive. 

Check out the [Microsoft dev guidelines](https://msdn.microsoft.com/en-us/library/dn742466.aspx) for reference

**Comment by dami-gg** [comment]
Good to know. So we keep it like this. Thanks for the clarification
