### ISSUE TITLE
Simple icon buttons

### ISSUE THREAD

**Issue by dami-gg** [zalando/dress-code#92]
Right now we have the icon buttons looking as an actual button with borders and coloured background.

We need even more simple buttons like the ones attached where only the shape of the icon is displayed

![screen shot 2016-02-02 at 15 18 19](https://cloud.githubusercontent.com/assets/3198244/12751940/3f5b530a-c9c0-11e5-931a-0708dbfb6dd5.png)

**Comment by rbarilani** [comment]
@dami-gg  What if you try dc-link and inside a dc-font-icon?

**Comment by dami-gg** [comment]
forgot to close this one
