### ISSUE TITLE
Status indicator bubbles in DC

### ISSUE THREAD

**Issue by gabrielhl** [zalando/dress-code#96]
The status indicator bubbles for New, Active, Inactive (or Offline/Online) are not available in DC and each team is creating their own independently. Let's make this a shared element in DC.

**Comment by gabrielhl** [comment]
@dami-gg @cjhowald @TomTomaso You are all concerned by this! Are you currently using any other status beside the three I mentioned? Also: where does this go? It's currently always used in tables but could potentially be appended to any text.

**Comment by TomTomaso** [comment]
can you explain it more detailed? i can not follow...

**Comment by gabrielhl** [comment]
@TomTomaso Sorry in your case the problem is that the design mockup didn't follow the same standard that everyone else is using. But we are going to align that to the rest.

![Brand CMS](https://cloud.githubusercontent.com/assets/31034/12978658/9d6c541c-d0d2-11e5-801d-c6bae7b19bc7.png)


![Users List](https://cloud.githubusercontent.com/assets/31034/12978651/8d6fe88a-d0d2-11e5-8f3f-64711b065ada.png)


![Article List](https://cloud.githubusercontent.com/assets/31034/12978622/5b1228e4-d0d2-11e5-8adc-20123c26f1b4.png)

![Dress Code (Proposal)](https://cloud.githubusercontent.com/assets/31034/12978632/6ca535ec-d0d2-11e5-86c4-12314cb57966.png)

**Comment by dami-gg** [comment]
We also use it in the user detail page since a few days ago but it will work the same way since we use the same code in an AngularJS directive

![screen shot 2016-02-15 at 09 38 47](https://cloud.githubusercontent.com/assets/3198244/13043368/0d6342d8-d3c8-11e5-83ca-7f31458cebc3.png)
